name: test

on: 
  push: 
    branches: 
      - main
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo hello
      - run: npm install
      - run: npm run build # dotnet build dotnet restore 
      - run: npm run test
